rDNA_variant_detection <- function(depth_cutoff = 100, SB_threshold = 0.80, fraction_cutoff = 0.02, proportion_cutoff = 0.02, input_directory = './'){
  
  # Read all variation files generated by Pysamstats in the specified input directory.
  files <- list.files(path = input_directory, '*45S.variation_strand.txt')
  samples <- sapply(strsplit(files, split='["."]'), "[", 1)
  
  # Declare types of variants. 
  Levels <- data.frame(rbind(c('Del', 'Ins', 'A', 'C', 'T', 'G'), seq(1:6)),stringsAsFactors=FALSE)
  
  # Load Reference sequence from first variation file in the input directory.
  Reference <- read.table(paste(input_directory, files[1], sep = '/'), comment.char="", header=TRUE, colClasses = c(rep("NULL", 2), "character", rep("NULL", 60)), sep="\t")
  
  # Calculation of variant frequencies with Strand Bias (SB) test for the major-alternative allele only.
  for(index in 1:length(files)){
    chr45S <- read.table(paste(input_directory, files[index], sep = '/'), comment.char="", header=TRUE, colClasses = c(rep("NULL", 3),"numeric", rep("NULL", 17), "numeric", rep("NULL", 5), "numeric", rep("NULL", 5), "numeric", rep("NULL", 5), "numeric", rep("NULL", 5), "numeric", rep("NULL", 5), "numeric", rep("NULL", 11)), sep="\t")
    chr45S_ <- read.table(paste(input_directory, files[index], sep = '/'), comment.char="", header=TRUE, colClasses = c(rep("NULL", 22), rep("numeric", 2), rep("NULL", 4), rep("numeric", 2), rep("NULL", 4), rep("numeric", 2), rep("NULL", 4), rep("numeric", 2), rep("NULL", 4), rep("numeric", 2), rep("NULL", 4), rep("numeric", 2), rep("NULL", 9)), sep="\t")
    
    chr45S <- cbind(chr45S, chr45S_)
    #chr45S[,1] <- chr45S[,2] + chr45S[,4] + chr45S[,5] + chr45S[,6] + chr45S[,7]
    chr45S[,1] <- sapply(chr45S[,1], function(x){if(x< depth_cutoff ){x<-NA}else{x<-x}})
    chr45S[,2:7] <- chr45S[,2:7] / chr45S[,1]
    
    # Estimate Strand Bias (SB)   
    for(i in 1: dim(chr45S)[1]){
      ref_level <- which(Levels[1,] == Reference$ref[i])
      Levels_temp <- Levels[,-ref_level]
      whom <- max(chr45S[i,1+as.numeric(Levels_temp[2,])])
      whom.index <- as.numeric(Levels_temp[2,which.max(chr45S[i,1+as.numeric(Levels_temp[2,])])])
      
      a <- chr45S[i, ref_level*2+6]
      b <- chr45S[i, whom.index*2+6]
      c <- chr45S[i, ref_level*2+7]
      d <- chr45S[i, whom.index*2+7]
      
      if(is.na(whom)){next
      }else if(whom > (1-fraction_cutoff)){next
      }else if(whom > fraction_cutoff){
        #flip major and minor allele if necessary
        if((a+c) >= (b+d)){
          chr45S[i,20] <-  abs ( b/(a+b) - d/(c+d) ) / ((b+d)/(a+b+c+d))
        }else if((a+c) < (b+d)){
          chr45S[i,20] <-  abs ( a/(b+a) - c/(d+c) ) / ((a+c)/(c+a+d+c))
        }
        if(is.na(chr45S[i,20])){next
        }else if(chr45S[i,20] >= SB_threshold ){chr45S[i,whom.index+1] <- NA
        }else{next}
      }else{chr45S[i,20] <- NA}
    }
    chr45S <- chr45S[,-c(8:19)]
    colnames(chr45S) <- c(paste('depth', samples[index], sep='.'), paste('Del', samples[index], sep='.'), paste('Ins', samples[index], sep='.'), paste('A', samples[index], sep='.'), paste('C', samples[index], sep='.'), paste('T', samples[index], sep='.'), paste('G', samples[index], sep='.'), paste('SB', samples[index], sep='.'))
    Reference <- cbind(Reference, chr45S)
    # Print sample name and mean depth.
    print(c(samples[index], mean(chr45S[,1], na.rm=TRUE)))
  }
  
  # Collect specific columms.
  Del <- Reference[ ,seq(3, length(Reference), 8), drop=FALSE]
  Ins <- Reference[ ,seq(4, length(Reference), 8), drop=FALSE]
  A <- Reference[ ,seq(5, length(Reference), 8), drop=FALSE]
  C <- Reference[ ,seq(6, length(Reference), 8), drop=FALSE]
  T <- Reference[ ,seq(7, length(Reference), 8), drop=FALSE]
  G <- Reference[ ,seq(8, length(Reference), 8), drop=FALSE]
  SB <- Reference[ ,seq(9, length(Reference), 8), drop=FALSE]
  
  # Calculate number of samples for each variant (whether reference of alternative) above certain frequency threshold within individuals.  
  Proportion_variants <- Reference[ , 1, drop=FALSE]
  Proportion_variants$Del <- apply(Del, 1, function(x){length(which(x >= proportion_cutoff))})
  Proportion_variants$Ins <- apply(Ins, 1, function(x){length(which(x >= proportion_cutoff))})
  Proportion_variants$A <- apply(A, 1, function(x){length(which(x >= proportion_cutoff))})
  Proportion_variants$C <- apply(C, 1, function(x){length(which(x >= proportion_cutoff))})
  Proportion_variants$T <- apply(T, 1, function(x){length(which(x >= proportion_cutoff))})
  Proportion_variants$G <- apply(G, 1, function(x){length(which(x >= proportion_cutoff))})
  Proportion_variants$Variant <- apply(Proportion_variants[,2:7], 1, sum)
  
  # Flag variants present in at least one individual.
  variants <- Proportion_variants
  variants$Pos <- rownames(variants)
  
  for(i in 1:dim(variants)[1]){
    what_level <- which(Levels[1,] == as.character(variants[i,1]))
    variants[i, what_level+1] <- NA
    Levels_temp <- Levels[1, which(variants[i,2:7]>0)]
    counter <- 1
    if(length(Levels_temp) > 1){
      variants[i,8] <- Levels_temp[1]
      while(counter < length(Levels_temp)){
        counter <- counter+1
        dimension <- dim(variants)[1] + 1
        variants[dimension,] <- variants[i,]
        variants[dimension, 8] <- Levels_temp[counter]
        print(dimension)
      }
    }else if(length(Levels_temp) == 1){
      variants[i,8] <- Levels_temp[1]
    }else{
      variants[i,8] <- NA
    }
  }
  
  # Remove invariable positions.
  variants <- variants[!is.na(variants$Variant),]
  # Add empty columns for each sample. 
  variants[,samples] <- NA
  
  # Proportion of samples with an alternative allele
  number_samples <- length(samples)
  
  for(i in 1:dim(variants)[1]){
    if(variants[i,8]=='Del'){
      variants[i,10:(9+ number_samples)] <- unlist(c(Reference[variants[i,9],seq(3, length(Reference), by=8 )]))
    }else if(variants[i,8]=='Ins'){
      variants[i,10:(9+ number_samples)] <- unlist(c(Reference[variants[i,9],seq(4, length(Reference), by=8 )]))
    }else if(variants[i,8]=='A'){
      variants[i,10:(9+ number_samples)] <- unlist(c(Reference[variants[i,9],seq(5, length(Reference), by=8 )]))
    }else if(variants[i,8]=='C'){
      variants[i,10:(9+ number_samples)] <- unlist(c(Reference[variants[i,9],seq(6, length(Reference), by=8 )]))
    }else if(variants[i,8]=='T'){
      variants[i,10:(9+ number_samples)] <- unlist(c(Reference[variants[i,9],seq(7, length(Reference), by=8 )]))
    }else if(variants[i,8]=='G'){
      variants[i,10:(9+ number_samples)] <- unlist(c(Reference[variants[i,9],seq(8, length(Reference), by=8 )]))
    }
    # Add data from reference allele for each variable position. 
    what_level <- which(Levels[1,] == as.character(variants[i,1]))
    variants[dim(variants)[1]+1,1:9] <- variants[i,1:9]
    variants[dim(variants)[1],8] <- 'ref'
    variants[dim(variants)[1],10:(9+ number_samples)] <- unlist(c(Reference[variants[i,9],seq(what_level +2, length(Reference), by=8 )]))
  }
  
  # Sort all variants by position.
  variants$Pos <- as.numeric(variants$Pos)
  variants <- variants[order(variants$Pos), ]
  
  # Remove duplicated 'ref' alleles originated from multi-allelic sites. 
  variants <- variants[ !duplicated(variants), ]
  
  # Transform data to a phenotype-like matrix.
  phen <- variants[ which(!duplicated(paste(variants$Pos, variants$ref, variants$Variant, sep='.'))), ]
  rownames(phen) <- paste(phen$Pos, phen$ref, phen$Variant, sep='.')
  phen <- phen[, -c(1:9),   drop=FALSE]
  phen <- data.frame(t(phen))
  Names <- data.frame(rownames(phen))
  colnames(Names) <- 'sample_id'
  Names$sample_id <- as.character(Names$sample_id)
  phen <- cbind(Names,phen)
  
  Variation_output <- list(samples=samples, Reference=Reference, proportion_cutoff=proportion_cutoff, Proportion_variants=Proportion_variants, phen=phen)
  
  return(Variation_output)
  
}
